export const GET_INDEX_ORGANIZATION = 'GET_INDEX_ORGANIZATION';
export const GET_SHOW_ORGANIZATION = 'GET_SHOW_ORGANIZATION';
export const CREATED_ORGANIZATION = 'CREATED_ORGANIZATION';
export const DESTROYED_ORGANIZATION = 'DESTROYED_ORGANIZATION';
export const UPDATED_ORGANIZATION = 'UPDATED_ORGANIZATION';

export default {
    GET_INDEX_ORGANIZATION,
    GET_SHOW_ORGANIZATION,
    CREATED_ORGANIZATION,
    DESTROYED_ORGANIZATION,
    UPDATED_ORGANIZATION
};